name: CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and release latest snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set version
        run: echo "latest" > version.txt

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup build tools
        run: npm install -g yo bower grunt-cli generator-karma generator-angular
      
      - name: Build with Grunt
        run: npm install && bower install && grunt build --force

      - name: Git tag
        run: git tag -f snapshot && git push --tags -f

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: snapshot
          name: latest-snapshot
          prerelease: true
          gzip: false
          allow_override: true
          files: frontend-latest.tar.gz